import {db,error,json,ws} from '@appdeploy/sdk';
const TABLE='entity_subscriptions';
type Subscription={id:string;entity_type:string;entity_id:string;connection_id:string;created_at:number};
async function list(){const{items}=await db.list<Subscription>(TABLE,{limit:1000});return items as Subscription[]}
export async function removeSubscriptionsByConnection(connectionId:string){const items=await list();const ids=items.filter(x=>x.connection_id===connectionId).map(x=>x.id);if(ids.length)await db.delete(TABLE,ids)}
export async function addSubscription(entityType:string,entityId:string,connectionId:string){const current=await list();if(current.some(x=>x.entity_type===entityType&&x.entity_id===entityId&&x.connection_id===connectionId))return;await db.add(TABLE,[{entity_type:entityType,entity_id:entityId,connection_id:connectionId,created_at:Date.now()}])}
export async function removeSubscriptions(entityType:string,entityId:string,connectionId:string){const items=await list();const ids=items.filter(x=>x.entity_type===entityType&&x.entity_id===entityId&&x.connection_id===connectionId).map(x=>x.id);if(ids.length)await db.delete(TABLE,ids)}
export async function notifySubscribers(entityType:string,entityId:string,payload:unknown,excludeConnectionId?:string){const items=await list();const ids=Array.from(new Set(items.filter(x=>x.entity_type===entityType&&x.entity_id===entityId&&x.connection_id!==excludeConnectionId).map(x=>x.connection_id)));if(!ids.length)return;await ws.send(ids,{v:1,type:'entity.update',payload:{entity_type:entityType,entity_id:entityId,data:payload}})}
export const realtimeSubscriptionRoutes={'POST /api/subscriptions':[async({body})=>{const b=(body||{}) as Record<string,string>;if(!b.entity_type||!b.entity_id||!b.connection_id)return error('entity_type, entity_id, connection_id are required',400);await addSubscription(b.entity_type,b.entity_id,b.connection_id);return json({ok:true})}], 'POST /api/subscriptions/remove':[async({body})=>{const b=(body||{}) as Record<string,string>;if(!b.entity_type||!b.entity_id||!b.connection_id)return error('entity_type, entity_id, connection_id are required',400);await removeSubscriptions(b.entity_type,b.entity_id,b.connection_id);return json({ok:true})}]};
