import {randomUUID} from 'node:crypto';
import {db,error,json} from '@appdeploy/sdk';
import {notifySubscribers} from './realtime-subscribers';
type RoomVideo={id:string;title:string;creator:string;creatorKey:string;published:string;category:string;source:'latest'|'curated'|'live'|'clip';channelUrl:string};type Participant={id:string;token:string;name:string;role:'host'|'guest';joinedAt:number;lastSeenAt:number;connectionId?:string|null};type Message={id:string;participantId:string;name:string;kind:'chat'|'prayer'|'scripture';text:string;at:number};type Reaction={id:string;participantId:string;name:string;emoji:string;at:number};type Playback={status:'playing'|'paused';position:number;updatedAt:number;revision:number};type Room={code:string;hostParticipantId:string;video:RoomVideo;playback:Playback;participants:Participant[];messages:Message[];reactions:Reaction[];createdAt:number;expiresAt:number;ended:boolean};type ActiveRoom=Room&{id:string};
const TABLE='watch_together_rooms';const TTL=24*60*60*1000;const MAX_PARTICIPANTS=12;const WATCH_URL='https://nfcps-book-library-c2ma7y.v2.appdeploy.ai/watch/';const CODE_CHARS='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
const cleanName=(raw:unknown)=>String(raw||'').replace(/\s+/g,' ').trim().slice(0,32);const cleanCode=(raw:unknown)=>String(raw||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6);const cleanText=(raw:unknown)=>String(raw||'').replace(/\s+/g,' ').trim().slice(0,280);const makeCode=()=>Array.from({length:6},()=>CODE_CHARS[Math.floor(Math.random()*CODE_CHARS.length)]).join('');
async function rooms(){const{items}=await db.list<Room>(TABLE,{limit:100});return items as ActiveRoom[]}
async function findRoom(codeRaw:unknown){const code=cleanCode(codeRaw);if(code.length!==6)return null;const list=await rooms();const expired=list.filter(x=>x.expiresAt<Date.now());if(expired.length)await db.delete(TABLE,expired.map(x=>x.id));return list.find(x=>x.code===code&&x.expiresAt>=Date.now())||null}
async function uniqueCode(){const used=new Set((await rooms()).filter(x=>x.expiresAt>=Date.now()).map(x=>x.code));for(let i=0;i<20;i++){const code=makeCode();if(!used.has(code))return code}return makeCode()}
const publicRoom=(r:ActiveRoom)=>({id:r.id,code:r.code,hostParticipantId:r.hostParticipantId,video:r.video,playback:r.playback,participants:r.participants.map(p=>({id:p.id,name:p.name,role:p.role,online:Boolean(p.connectionId),joinedAt:p.joinedAt})),messages:r.messages,reactions:r.reactions.slice(-18),createdAt:r.createdAt,expiresAt:r.expiresAt,ended:r.ended,shareUrl:`${WATCH_URL}?room=${r.code}`});
async function save(room:ActiveRoom,patch:Partial<Room>,notify=true){const{id,...record}=room;const next:Room={...record,...patch};const[ok]=await db.update(TABLE,[{id,record:next}]);if(!ok)throw new Error('Could not update Watch Together room');const active={...next,id} as ActiveRoom;if(notify)await notifySubscribers('watch_room',id,publicRoom(active));return active}
const member=(room:ActiveRoom,tokenRaw:unknown)=>room.participants.find(p=>p.token===String(tokenRaw||''));const isHost=(room:ActiveRoom,p?:Participant)=>Boolean(p&&p.id===room.hostParticipantId);
export async function markRoomConnectionsOffline(connectionId:string){const list=await rooms();for(const room of list){if(room.expiresAt<Date.now()||room.ended)continue;let changed=false;const participants=room.participants.map(p=>{if(p.connectionId!==connectionId)return p;changed=true;return{...p,connectionId:null,lastSeenAt:Date.now()}});if(changed)await save(room,{participants})}}
export const watchTogetherRoutes={
'POST /api/watch/rooms':[async({body})=>{const b=(body||{}) as {video?:RoomVideo;name?:string};const name=cleanName(b.name);const v=b.video;if(!name||name.length<2)return error('Enter a name with at least 2 characters.',400);if(!v||!/^[A-Za-z0-9_-]{11}$/.test(String(v.id||''))||!v.title||!v.creator)return error('A valid Watch video is required.',400);const now=Date.now();const participant:Participant={id:randomUUID(),token:randomUUID(),name,role:'host',joinedAt:now,lastSeenAt:now,connectionId:null};const room:Room={code:await uniqueCode(),hostParticipantId:participant.id,video:{...v,id:String(v.id),title:String(v.title).slice(0,180),creator:String(v.creator).slice(0,100),category:String(v.category||'Christian Growth').slice(0,60),creatorKey:String(v.creatorKey||'trusted').slice(0,60),published:String(v.published||new Date().toISOString()),source:v.source||'curated',channelUrl:String(v.channelUrl||'').slice(0,500)},playback:{status:'paused',position:0,updatedAt:now,revision:1},participants:[participant],messages:[],reactions:[],createdAt:now,expiresAt:now+TTL,ended:false};const[id]=await db.add(TABLE,[room]);if(!id)return error('Could not create Watch Together room.',500);const active={...room,id} as ActiveRoom;return json({room:publicRoom(active),participantToken:participant.token,participantId:participant.id},201)}],
'GET /api/watch/rooms/:code':[async({params})=>{const room=await findRoom(params.code);if(!room)return error('This Watch Together room was not found or has expired.',404);return json({room:publicRoom(room)})}],
'POST /api/watch/rooms/:code/join':[async({params,body})=>{const room=await findRoom(params.code);if(!room)return error('This Watch Together room was not found or has expired.',404);if(room.ended)return error('This Watch Together room has ended.',410);const b=(body||{}) as {name?:string};const name=cleanName(b.name);if(name.length<2)return error('Enter a name with at least 2 characters.',400);if(room.participants.length>=MAX_PARTICIPANTS)return error('This Watch Together room is full.',409);const now=Date.now();const participant:Participant={id:randomUUID(),token:randomUUID(),name,role:'guest',joinedAt:now,lastSeenAt:now,connectionId:null};const next=await save(room,{participants:[...room.participants,participant]});return json({room:publicRoom(next),participantToken:participant.token,participantId:participant.id})}],
'POST /api/watch/rooms/:code/presence':[async({params,body})=>{const room=await findRoom(params.code);if(!room)return error('Room not found.',404);const b=(body||{}) as {participantToken?:string;connectionId?:string};const p=member(room,b.participantToken);if(!p)return error('Your room session is no longer active.',403);const connectionId=String(b.connectionId||'').slice(0,180);if(!connectionId)return error('A realtime connection is required.',400);const participants=room.participants.map(x=>x.id===p.id?{...x,connectionId,lastSeenAt:Date.now()}:x);const next=await save(room,{participants});return json({room:publicRoom(next)})}],
'POST /api/watch/rooms/:code/state':[async({params,body})=>{const room=await findRoom(params.code);if(!room)return error('Room not found.',404);if(room.ended)return error('This room has ended.',410);const b=(body||{}) as {participantToken?:string;status?:string;position?:number};const p=member(room,b.participantToken);if(!isHost(room,p))return error('Only the room host can control synchronized playback.',403);const status=b.status==='playing'?'playing':b.status==='paused'?'paused':null;if(!status)return error('Playback status must be playing or paused.',400);const position=Math.max(0,Math.min(21600,Number(b.position)||0));const next=await save(room,{playback:{status,position,updatedAt:Date.now(),revision:room.playback.revision+1},participants:room.participants.map(x=>x.id===p!.id?{...x,lastSeenAt:Date.now()}:x)});return json({room:publicRoom(next)})}],
'POST /api/watch/rooms/:code/message':[async({params,body})=>{const room=await findRoom(params.code);if(!room)return error('Room not found.',404);if(room.ended)return error('This room has ended.',410);const b=(body||{}) as {participantToken?:string;text?:string;kind?:string};const p=member(room,b.participantToken);if(!p)return error('Join the room before sending a message.',403);const text=cleanText(b.text);if(!text)return error('Write a message first.',400);const kind:Message['kind']=b.kind==='prayer'?'prayer':b.kind==='scripture'?'scripture':'chat';const msg:Message={id:randomUUID(),participantId:p.id,name:p.name,kind,text,at:Date.now()};const next=await save(room,{messages:[...room.messages,msg].slice(-60),participants:room.participants.map(x=>x.id===p.id?{...x,lastSeenAt:Date.now()}:x)});return json({room:publicRoom(next)})}],
'POST /api/watch/rooms/:code/reaction':[async({params,body})=>{const room=await findRoom(params.code);if(!room)return error('Room not found.',404);if(room.ended)return error('This room has ended.',410);const b=(body||{}) as {participantToken?:string;emoji?:string};const p=member(room,b.participantToken);if(!p)return error('Join the room before reacting.',403);const emoji=['❤️','🙏','🔥','🙌','📖','💡'].includes(String(b.emoji))?String(b.emoji):'🙏';const reaction:Reaction={id:randomUUID(),participantId:p.id,name:p.name,emoji,at:Date.now()};const next=await save(room,{reactions:[...room.reactions,reaction].slice(-30)});return json({room:publicRoom(next)})}],
'POST /api/watch/rooms/:code/leave':[async({params,body})=>{const room=await findRoom(params.code);if(!room)return error('Room not found.',404);const b=(body||{}) as {participantToken?:string};const p=member(room,b.participantToken);if(!p)return json({left:true});const participants=isHost(room,p)?room.participants.map(x=>x.id===p.id?{...x,connectionId:null,lastSeenAt:Date.now()}:x):room.participants.filter(x=>x.id!==p.id);const next=await save(room,{participants});return json({left:true,room:publicRoom(next)})}],
'POST /api/watch/rooms/:code/end':[async({params,body})=>{const room=await findRoom(params.code);if(!room)return error('Room not found.',404);const b=(body||{}) as {participantToken?:string};const p=member(room,b.participantToken);if(!isHost(room,p))return error('Only the host can end this room.',403);const next=await save(room,{ended:true,playback:{...room.playback,status:'paused',updatedAt:Date.now(),revision:room.playback.revision+1}});return json({room:publicRoom(next)})}]
};
