'use client';
import {useEffect,useState} from 'react';
import {BookOpen,ChevronRight,Play} from 'lucide-react';
import {openReader,type ReaderBook} from './ReaderExperience';
import ConceptBookCover from './ConceptBookCover';
type ReaderRecord={book:ReaderBook;progress:number;lastOpened:number};
const FALLBACK:ReaderBook={id:25141,title:'The Pursuit of God',author:'A. W. Tozer',cover:'https://www.gutenberg.org/cache/epub/25141/pg25141.cover.medium.jpg',summary:'A devotional classic about seeking God Himself.',formats:{'image/jpeg':'https://www.gutenberg.org/cache/epub/25141/pg25141.cover.medium.jpg','text/plain; charset=utf-8':'https://www.gutenberg.org/cache/epub/25141/pg25141.txt','text/html':'https://www.gutenberg.org/cache/epub/25141/pg25141-images.html','application/epub+zip':'https://www.gutenberg.org/ebooks/25141.epub3.images'}};
const SCENE='https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1600&q=88';
export default function HomeV3({greeting,current,onGoRead,watchHref}:{greeting:string;current:ReaderRecord|null;onGoRead:()=>void;watchHref:string}){const[name,setName]=useState('');useEffect(()=>{try{setName(localStorage.getItem('nfcps-watch-name')||localStorage.getItem('nfcps-profile-name')||'')}catch{}},[]);const book=current?.book||FALLBACK;const progress=Math.max(0,Math.min(100,current?.progress||0));const openFocus=()=>current?openReader(book):onGoRead();return <section className='cx-home' style={{backgroundImage:`url(${SCENE})`}}><div className='cx-home-overlay'/><div className='cx-home-inner'><div className='cx-home-bar'><button onClick={onGoRead} className='cx-brand'><img src='/resources/nfcps-logo.png' alt='NFCPS'/><span><strong>NFCPS One</strong><small>Christ, the Therapy for All.</small></span></button><span className='cx-avatar'>{(name||'N').charAt(0).toUpperCase()}</span></div><div className='cx-home-greeting'><small>{greeting},</small><h1>{name||'Welcome back.'}</h1><p>Stillness today. Strength tomorrow.</p></div><div className='cx-home-focus'><ConceptBookCover id={book.id} title={book.title} author={book.author}/><div className='cx-home-focus-copy'><small>{current?'CONTINUE READING':'BEGIN HERE'}</small><h2>{book.title}</h2><p>{book.author}</p>{current&&<div className='cx-progress'><i style={{width:`${Math.max(3,progress)}%`}}/><span>{Math.round(progress)}%</span></div>}</div></div><button className='cx-primary cx-home-continue' onClick={openFocus}><BookOpen/>{current?'Continue':'Start reading'}<ChevronRight/></button><section className='cx-home-today'><div className='cx-section-title'><h3>For You Today</h3><a href={watchHref}>See all <ChevronRight/></a></div><div className='cx-today-track'><a className='cx-today-card' href={watchHref}><img src='https://i.ytimg.com/vi/3RHdq_h0ZH4/maxresdefault.jpg' alt='Featured sermon'/><span><small>WATCH</small><strong>The Power of Prayer</strong><em>Apostle Michael Orokpo</em></span><i><Play/></i></a><button className='cx-today-card quiet' onClick={onGoRead}><img src='https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?auto=format&fit=crop&w=700&q=75' alt='Quiet landscape'/><span><small>READ</small><strong>Rest in His Presence</strong><em>Open your reading shelf</em></span><i><BookOpen/></i></button></div></section></div></section>}
