'use client';
import {useMemo,useState} from 'react';
import {ArrowLeft,Search} from 'lucide-react';
import {books} from './Library';
import {CirculationAction} from './Circulation';
type Book=(typeof books)[number];
function PhysicalCover({book}:{book:Book}){const[bad,setBad]=useState(false);return <span className='cx-physical-cover'>{book.cover&&!bad?<img src={book.cover} alt={`${book.title} cover`} onError={()=>setBad(true)}/>:<span><small>NFCPS LIBRARY</small><strong>{book.title}</strong><em>{book.author}</em></span>}</span>}
function Tile({book,onOpen}:{book:Book;onOpen:(b:Book)=>void}){return <button className='cx-library-book' onClick={()=>onOpen(book)}><PhysicalCover book={book}/><span><strong>{book.title}</strong><small>{book.author}</small></span></button>}
export default function LibraryV3(){const[q,setQ]=useState('');const[category,setCategory]=useState('All');const[selected,setSelected]=useState<Book|null>(null);const categories=useMemo(()=>['All',...Array.from(new Set(books.map(b=>b.category))).slice(0,5)],[]);const filtered=useMemo(()=>{const n=q.trim().toLowerCase();return books.filter(b=>(category==='All'||b.category===category)&&(!n||`${b.title} ${b.author} ${b.category}`.toLowerCase().includes(n)))},[q,category]);const prayer=filtered.filter(b=>b.category==='Prayer'||/prayer/i.test(b.title));const leadership=filtered.filter(b=>b.category==='Leadership'||b.category==='Bible Study');return <section className='cx-library-page'><div className='cx-library-bar'><div><h1>Library</h1><p>Discover. Borrow. Grow.</p></div><span className='cx-avatar'>N</span></div><label className='cx-library-search'><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder='Search physical books'/></label><div className='cx-library-filters'>{categories.map(x=><button key={x} className={category===x?'active':''} onClick={()=>setCategory(x)}>{x}</button>)}</div><section className='cx-library-shelf'><div className='cx-section-title'><h2>Physical Collection</h2><span>{filtered.length} books</span></div><div className='cx-library-track'>{filtered.slice(0,12).map(b=><Tile key={b.id} book={b} onOpen={setSelected}/>)}</div></section>{prayer.length>0&&<section className='cx-library-shelf'><div className='cx-section-title'><h2>Prayer</h2></div><div className='cx-library-track'>{prayer.map(b=><Tile key={`p-${b.id}`} book={b} onOpen={setSelected}/>)}</div></section>}{leadership.length>0&&<section className='cx-library-shelf'><div className='cx-section-title'><h2>Leadership & Study</h2></div><div className='cx-library-track'>{leadership.map(b=><Tile key={`l-${b.id}`} book={b} onOpen={setSelected}/>)}</div></section>}{selected&&<section className='cx-physical-detail'><div className='cx-detail-top dark'><button onClick={()=>setSelected(null)}><ArrowLeft/></button><span>Physical Book</span><i/></div><div className='cx-physical-detail-body'><PhysicalCover book={selected}/><small>{selected.category}</small><h1>{selected.title}</h1><p className='cx-detail-author'>{selected.author}</p><p>{selected.description}</p><CirculationAction book={selected}/></div></section>}</section>}
