'use client';
import {useEffect,useMemo,useState} from 'react';
import {BookOpen,Download,LoaderCircle,Search} from 'lucide-react';
import {api} from '@appdeploy/client';
import {openReader,type ReaderBook} from './ReaderExperience';

type ReaderRecord={book:ReaderBook;progress:number;lastOpened:number};
type EBook={id:number;title:string;authors:{name:string}[];subjects:string[];summaries?:string[];formats:Record<string,string>};type EResponse={count:number;next:string|null;results:EBook[];degraded?:boolean};
const make=(id:number,title:string,name:string,subjects:string[],summary:string):EBook=>({id,title,authors:[{name}],subjects,summaries:[summary],formats:{'image/jpeg':`https://www.gutenberg.org/cache/epub/${id}/pg${id}.cover.medium.jpg`,'text/plain; charset=utf-8':`https://www.gutenberg.org/cache/epub/${id}/pg${id}.txt`,'text/html':`https://www.gutenberg.org/cache/epub/${id}/pg${id}-images.html`,'application/epub+zip':`https://www.gutenberg.org/ebooks/${id}.epub3.images`}});
const STARTER:EBook[]=[make(25141,'The Pursuit of God','A. W. Tozer',['Christianity','Prayer','Devotional literature'],'A devotional classic about seeking God Himself.'),make(131,"The Pilgrim's Progress",'John Bunyan',['Christianity','Faith','Allegories'],'A Christian allegory of perseverance and faith.'),make(1653,'The Imitation of Christ','Thomas à Kempis',['Christianity','Spiritual life'],'A classic on humility and following Christ.'),make(57121,'Humility: The Beauty of Holiness','Andrew Murray',['Christianity','Holiness','Humility'],'Andrew Murray on Christlike humility.'),make(16769,'Orthodoxy','G. K. Chesterton',['Christianity','Apologetics','Theology'],'A lively Christian classic about faith and wonder.'),make(26709,'Lord, Teach Us To Pray','Andrew Murray',['Christianity','Prayer','Devotional literature'],'Practical teaching on learning prayer from Christ.')];
const topics=['All','Prayer','Bible','Theology','Devotional literature'];const author=(b:EBook)=>b.authors.length?b.authors.map(a=>a.name.replace(/, ([^,]+)$/,' $1')).join(', '):'Unknown author';const cover=(b:EBook)=>b.formats['image/jpeg']||'';const download=(b:EBook)=>b.formats['application/epub+zip']||b.formats['text/html']||`https://www.gutenberg.org/ebooks/${b.id}`;const readerBook=(b:EBook):ReaderBook=>({id:b.id,title:b.title,author:author(b),formats:b.formats,cover:cover(b),summary:b.summaries?.[0]});const merge=(a:EBook[],b:EBook[])=>Array.from(new Map([...a,...b].map(x=>[x.id,x])).values());
function Tile({book,featured=false}:{book:EBook;featured?:boolean}){const[bad,setBad]=useState(false);return <article className={featured?'readv2-book featured':'readv2-book'}><button className='readv2-cover' onClick={()=>openReader(readerBook(book))}>{cover(book)&&!bad?<img src={cover(book)} alt={`${book.title} cover`} onError={()=>setBad(true)} loading='lazy'/>:<span><small>NFCPS</small><strong>{book.title}</strong><em>{author(book)}</em></span>}</button><div className='readv2-meta'><h3>{book.title}</h3><p>{author(book)}</p><div><button onClick={()=>openReader(readerBook(book))}><BookOpen/>Read</button><a href={download(book)} target='_blank' rel='noreferrer' aria-label={`Download ${book.title}`}><Download/></a></div></div></article>}
function Shelf({title,books}:{title:string;books:EBook[]}){if(!books.length)return null;return <section className='readv2-shelf'><header><h2>{title}</h2></header><div>{books.map((b,i)=><Tile key={`${title}-${b.id}`} book={b} featured={i===0}/>)}</div></section>}
export default function ReadV2({current}:{current:ReaderRecord|null}){const[books,setBooks]=useState<EBook[]>(STARTER);const[q,setQ]=useState('');const[topic,setTopic]=useState('All');const[loading,setLoading]=useState(false);const[degraded,setDegraded]=useState(false);useEffect(()=>{let live=true;setLoading(true);const params=new URLSearchParams({topic:topic==='All'?'Christianity':topic});if(q.trim())params.set('search',q.trim());api.get(`/api/ebooks/catalog?${params}`).then(r=>{if(!live)return;const data=r.data as EResponse;const incoming=Array.isArray(data.results)?data.results.filter(x=>x?.id&&x?.title):[];const next=merge(STARTER,incoming);setBooks(next.length?next:STARTER);setDegraded(Boolean(data.degraded))}).catch(()=>{if(live){setBooks(STARTER);setDegraded(true)}}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[topic,q]);const filtered=useMemo(()=>{const needle=q.trim().toLowerCase();return books.filter(b=>{const text=`${b.title} ${author(b)} ${b.subjects.join(' ')}`.toLowerCase();const topicOk=topic==='All'||text.includes(topic.toLowerCase());return topicOk&&(!needle||text.includes(needle))})},[books,q,topic]);const prayer=filtered.filter(b=>`${b.subjects.join(' ')} ${b.title}`.toLowerCase().includes('prayer')).slice(0,8);const classics=filtered.filter(b=>[25141,131,1653,57121,16769,26709].includes(b.id)).slice(0,8);const forYou=filtered.slice(0,8);return <section className='readv2'><header className='readv2-head'><div><span>READ</span><h1>Reading</h1><p>Feed your spirit. One page at a time.</p></div><Search/></header>{current&&<button className='readv2-resume' onClick={()=>openReader(current.book)}><img src={current.book.cover||STARTER[0].formats['image/jpeg']} alt={`${current.book.title} cover`}/><span><small>CONTINUE READING</small><strong>{current.book.title}</strong><em>{current.book.author}</em><i><b style={{width:`${Math.max(3,Math.min(100,current.progress))}%`}}/></i><span>{Math.round(current.progress)}%</span></span></button>}<label className='readv2-search'><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder='Search books, authors or topics'/>{loading&&<LoaderCircle className='spin'/>}</label><nav className='readv2-topics'>{topics.map(t=><button key={t} className={topic===t?'active':''} onClick={()=>setTopic(t)}>{t}</button>)}</nav>{degraded&&<p className='readv2-offline'>Your saved NFCPS shelf is available while the wider catalogue reconnects.</p>}{q.trim()?<section className='readv2-results'><h2>Results</h2>{filtered.length?<div>{filtered.slice(0,18).map(b=><Tile key={b.id} book={b}/>)}</div>:<p>No match yet. Try another title, author or topic.</p>}</section>:<><Shelf title='For You' books={forYou}/><Shelf title='Christian Classics' books={classics}/><Shelf title='Prayer & Devotion' books={prayer.length?prayer:forYou.slice(0,6)}/></>}</section>}
