plugins {
    id 'com.android.application'
}

android {
    namespace 'org.nfcpsunizik.one'
    compileSdk 35

    defaultConfig {
        applicationId 'org.nfcpsunizik.one'
        minSdk 24
        targetSdk 35
        versionCode 2
        versionName '1.1.0'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
